### ISSUE TITLE
Missing Themes for Version 1.54.0

### ISSUE THREAD

**Issue by darkeagle1337** [FusionAuth/fusionauth-theme-history#3]
After an email announcement from you pointing out a vulnerability that would be solved in version 1.54.0, we wanted to do this.
However, the themes from this repository are important for our upgrade process. 
Can you say until when the themes of version 1.54.0 will be available as a tag in this repository?

Thank you and greetings

Christian

**Comment by spwitt** [comment]
Thank you for the feedback. Sorry for the issue.

There were no theme changes from `1.53.3` to `1.54.0`.

I have created the tag and will follow up internally to be sure the tag is created automatically for future releases.

**Comment by spwitt** [comment]
We have identified the root cause and updated our automation to create the tag on release.
